const GAME_TYPE = {
  TOP_LINE: 'TOP_LINE',
  MIDDLE_LINE: 'MIDDLE_LINE',
  BOTTOM_LINE: 'BOTTOM_LINE',
  FULL_HOUSE: 'FULL_HOUSE',
  EARLY_FIVE: 'EARLY_FIVE'
};

const CLAIM_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED'
};

const LINE_INDEX = {
  [GAME_TYPE.TOP_LINE]: 0,
  [GAME_TYPE.MIDDLE_LINE]: 1,
  [GAME_TYPE.BOTTOM_LINE]: 2
};

module.exports = {
  GAME_TYPE,
  CLAIM_STATUS,
  LINE_INDEX
};
